### ISSUE TITLE
Unable to build awx-ee because of pip resolution

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx-ee#143]
I am building single image for both control plane EE and actual worker EE based on `quay.io/ansible/awx-ee:latest`.  
Since some recent time build is not able to finish at all because of same issue that described [in this question](https://serverfault.com/questions/1112486/awx-execution-environment-pip-error-resolutiontoodeep-2000000)

```
#17 19312.0   Downloading adal-0.6.0-py2.py3-none-any.whl (51 kB)
#17 19312.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 1.2 MB/s eta 0:00:00


#17 51133.3 ERROR: Exception:
#17 51133.3 Traceback (most recent call last):
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#17 51133.3     status = run_func(*args)
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#17 51133.3     return func(self, options, args)
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 339, in run
#17 51133.3     requirement_set = resolver.resolve(
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
#17 51133.3     result = self._result = resolver.resolve(
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#17 51133.3     state = resolution.resolve(requirements, max_rounds=max_rounds)
#17 51133.3   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
#17 51133.3     raise ResolutionTooDeep(max_rounds)
#17 51133.3 pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
#17 51133.7 WARNING: You are using pip version 22.0.3; however, version 22.2.2 is available.
#17 51133.7 You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
#17 ERROR: executor failed running [/bin/sh -c assemble]: exit code: 2
------
 > [builder 5/5] RUN assemble:
------
executor failed running [/bin/sh -c assemble]: exit code: 2

An error occured (rc=1), see output line(s) above for details.
```

Both requirements.txt and requirements.yml wasn't changed.
Also it's not quite clear based on what `quay.io/ansible/awx-ee:latest` is built, because it's updated quite frequently and not following this awx-ee project commits.

**Comment by twripley** [comment]
There is an issue in the community.vmware collection.

I can confirm by removing that one collection from requirements.yml, the build completes successfully.

~~Try pinning a specific version of that collection.~~
I've tried pinning the last 10 versions of community.vmware.  I can't build an EE with community.vmware.

I notice it pulls the current vsphere-automation-sdk when it builds.  Maybe there is a breaking change there.

```Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git (from -r /tmp/src/requirements.txt (line 59))
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-req-build-tj5f8k69
  Running command git clone --filter=blob:none --quiet https://github.com/vmware/vsphere-automation-sdk-python.git /tmp/pip-req-build-tj5f8k69
  Resolved https://github.com/vmware/vsphere-automation-sdk-python.git to commit a5ef74d9d91d0bc292a07ae1bb8460361b2d67e0
```

**Comment by adpavlov** [comment]
Indeed the issue is because of recent changes in `vsphere-automation-sdk`. There is an issue opened https://github.com/vmware/vsphere-automation-sdk-python/issues/339

**Comment by relrod** [comment]
I think this seems to not be an issue anymore (the ee is building fine lately, for me locally and on the daily builds). I think the issue might have worked itself out?

@adpavlov Can this be closed now?

**Comment by relrod** [comment]
Closing.
